apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkerboard
  labels:
    app: checkerboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkerboard
  template:
    metadata:
      labels:
        app: checkerboard
    spec:
      containers:
        - name: checkerboard
          image: lsstsqre/checkerboard:0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: checkerboard
          env:
            - name: LOGLEVEL
              value: INFO
            - name: CHECKERBOARD_USER
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: checkerboard.user
            - name: CHECKERBOARD_PW
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: checkerboard.pw
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: slack.app.token
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: slack.bot.token
