apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkerboard
  labels:
    app: checkerboard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: checkerboard
  template:
    metadata:
      labels:
        name: checkerboard
    spec:
      containers:
        - name: checkerboard
          imagePullPolicy: "Always"
          image: "lsstsqre/checkerboard"
          ports:
            - containerPort: 5000
              name: app
          envFrom:
            - configMapRef:
                name: checkerboard
          env:
            - name: CHECKERBOARD_USER
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: checkerboard.user
            - name: CHECKERBOARD_PW
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: checkerboard.pw
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: slack.app.token
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: checkerboard
                  key: slack.bot.token
