apiVersion: v1
kind: Service
metadata:
  name: u-ghslacker
  labels:
    app: u-ghslacker
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: u-ghslacker
