apiVersion: v1
kind: Service
metadata:
  name: checkerboard
  labels:
    app: checkerboard
spec:
  ports:
    - name: checkerboard-http
      protocol: TCP
      port: 5000
      targetPort: app
  selector:
    name: checkerboard
