apiVersion: v1
kind: Secret
metadata:
  name: u-ghslacker
stringData:
  # Username used to authenticate to ghslacker.
  ghslacker.user: "..."
  # Password used to authenticate to ghslacker.
  ghslacker.pw: "..."
  # Slack user token.
  slack.app.token: "..."
  # Slack bot token.
  slack.bot.token: "..."
