# TLS secrets for ssl-proxy
#
# From https://github.com/GoogleCloudPlatform/kube-jenkins-imager/blob/master/ssl_secrets.template.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ssl-proxy-secret
  namespace: default
data:
  # base64 -i example_org.crt
  tls.crt: 'FIXME'
  # base64 -i example_org.key
  tls.key: 'FIXME'
