apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: u-ghslacker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: u-ghslacker
    spec:
      containers:

        - name: u-ghslacker
          imagePullPolicy: "Always"
          image: "lsstsqre/uservice-ghslacker"
          ports:
            -
              containerPort: 5000
              name: u-ghslacker
          env:
            - name: LOGLEVEL
              value: DEBUG
            - name: GHSLACKER_USER
              valueFrom:
                secretKeyRef:
                  name: u-ghslacker
                  key: ghslacker.user
            - name: GHSLACKER_PW
              valueFrom:
                secretKeyRef:
                  name: u-ghslacker
                  key: ghslacker.pw
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: u-ghslacker
                  key: slack.app.token
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: u-ghslacker
                  key: slack.bot.token
                  
